### ISSUE TITLE
[FEAT] 커스터머 메인 화면 변경

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-customer#1]
## 📝 Description
브로커 메인 화면 기반 커스터머 메인 컴포넌트 개발

## 📍 Todo
- [x] 데일리 요약 컴포넌트 수정
- [x] 추천 업체 컴포넌트 개발
- [x] 최근 거래 내역 컴포넌트 개발
- [x] 출고 요청 이동 컴포넌트 개발
- [x] 관심 업체 컴포넌트 개발
