### ISSUE TITLE
[FEAT] 커스터머 메인 화면 기능 구현

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-customer#24]
## 📝 Description
커스터머 메인 화면 필요 기능 구현

## 📍 Todo
- [ ] 출고 내용 요약 조회
- [ ] 추천 매장 조회
- [ ] 최근 거래 매장 조회
