### ISSUE TITLE
[FEAT] 커스터머 팔로우 기능 구현

### ISSUE THREAD

**Issue by jang643** [8-palbochae/seahere-customer#31]
## 📝 Description
설명을 작성하세요.

## 📍 Todo
- [x] 회사 정보 BrokerInfo에 팔로우 여부 포함
- [x] 팔로우 목록 조회 기능 구현
- [x] 팔로우/언팔로우 시 모달 표출
- [x] 주거래업체 표시
